version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: questions_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: questions_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    networks:
      - questions-network

  backend:
    build: ./backend
    container_name: questions_backend
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=questions_db
      - DB_PORT=3306
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - questions-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: questions_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - questions-network

volumes:
  db_data:


networks:
  questions-network:
    driver: bridge
